name: smooth_page_indicator
description: Customizable animated page indicator with a set of built-in effects.
version: 0.1.1
author: Milad Akarie <milad.akarie@gmail.com>
homepage: https://github.com/Milad-Akarie/smooth_page_indicator

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
